# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hexagon.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhexagon.proto\"\xaa\x02\n\x07Hexagon\x12\x0e\n\x06map_id\x18\x01 \x01(\x05\x12\x12\n\nhexagon_id\x18\x02 \x01(\x05\x12\x19\n\x11position_relative\x18\x03 \x03(\x05\x12\x19\n\x11position_absolute\x18\x04 \x03(\x05\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\x14\n\x0chexagon_type\x18\x06 \x01(\t\x12\x14\n\x0chexagon_size\x18\x07 \x01(\t\x12\x15\n\rhexagon_shape\x18\x08 \x01(\t\x12\"\n\x08\x63ontours\x18\t \x03(\x0b\x32\x10.Hexagon.Contour\x12\x12\n\ncreated_at\x18\n \x01(\t\x12\x12\n\nupdated_at\x18\x0b \x01(\t\x1a#\n\x07\x43ontour\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hexagon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEXAGON']._serialized_start=18
  _globals['_HEXAGON']._serialized_end=316
  _globals['_HEXAGON_CONTOUR']._serialized_start=281
  _globals['_HEXAGON_CONTOUR']._serialized_end=316
# @@protoc_insertion_point(module_scope)
